import { CarSetup, TireCompound, TrackData } from './types';

export const DEFAULT_SETUP: CarSetup = {
  // Aero
  frontWing: 25,
  rearWing: 25,
  // Transmission
  onThrottleDiff: 75,
  offThrottleDiff: 60,
  // Suspension
  frontSuspension: 21,
  rearSuspension: 21,
  frontAntiRollBar: 11,
  rearAntiRollBar: 11,
  frontRideHeight: 35,
  rearRideHeight: 38,
  // Brakes
  brakePressure: 100,
  brakeBias: 56,
  // Tires
  frontTirePressure: 23.0,
  rearTirePressure: 21.0,
  tireCompound: TireCompound.MEDIUM,
};

export const SETUP_DESCRIPTIONS: Record<keyof CarSetup, string> = {
  frontWing: "직선 위주 트랙(몬자)은 낮게, 코너 위주(모나코)는 높게 설정하여 다운포스를 조절합니다.",
  rearWing: "프론트 윙과 밸런스를 맞추며, 높을수록 코너링 안정성이 좋아지지만 직선 속도가 줄어듭니다.",
  onThrottleDiff: "가속 시(온-스로틀) 90% 내외로 높게 설정하면 탈출 가속력이 좋아집니다.",
  offThrottleDiff: "감속 시(오프-스로틀) 45% 내외로 낮게 설정하면 코너 진입 회전이 부드러워집니다.",
  frontSuspension: "높음(41): 반응성 향상 / 낮음(1): 요철 흡수 및 안정성 증가.",
  rearSuspension: "프론트와 밸런스를 맞추며 트랙 요철과 연석 활용도에 따라 강성을 조절합니다.",
  frontAntiRollBar: "코너링 시 무게 이동을 제어합니다. 전륜은 보통 낮게 설정합니다.",
  rearAntiRollBar: "코너링 시 롤링을 제어합니다. 후륜은 보통 높게 설정하여 회전성을 돕습니다.",
  frontRideHeight: "낮을수록 무게중심이 낮아져 좋지만, 연석에 긁히지 않도록 주의해야 합니다.",
  rearRideHeight: "프론트보다 약간 높게 설정하여(레이크) 공기역학적 다운포스를 유도합니다.",
  brakePressure: "100%에 가까울수록 제동 거리가 짧아지지만, 바퀴 잠김(Lock-up) 위험이 커집니다.",
  brakeBias: "54% 기준. 앞바퀴가 잠기면 뒤로(낮게), 뒷바퀴가 잠기면 앞으로(높게) 조절합니다.",
  frontTirePressure: "전륜 기준 29 PSI 내외. 낮으면 접지력 증가, 높으면 반응성 증가 및 마모 가속.",
  rearTirePressure: "후륜 기준 26 PSI 내외. 트랙 온도와 타이어 종류에 따라 조절합니다.",
  tireCompound: "트랙 특성과 날씨에 맞춰 선택합니다 (소프트: 빠름/마모큼, 하드: 느림/오래감)."
};

// Wing angles updated to 0-50 scale (roughly x4 of previous 0-12)
export const TRACKS: TrackData[] = [
  {
    id: 'bahrain',
    name: '바레인 인터내셔널 서킷',
    country: '바레인',
    description: '긴 직선과 급제동 구간, 그리고 바람이 변수인 사막의 트랙입니다.',
    characteristics: { downforce: '중간', tireWear: '높음', speed: '중간' },
    baseLapTime: 91.4, 
    idealSetup: { wingAngle: 28, stiffness: 6 },
    sectors: ['Straight', 'Corner', 'Straight', 'Corner', 'Corner', 'Straight', 'Corner', 'Straight'],
  },
  {
    id: 'saudi',
    name: '제다 코니쉬 서킷',
    country: '사우디아라비아',
    description: '벽 사이를 질주하는 초고속 시가지 서킷으로 매우 위험합니다.',
    characteristics: { downforce: '낮음', tireWear: '중간', speed: '높음' },
    baseLapTime: 88.2, 
    idealSetup: { wingAngle: 15, stiffness: 7 },
    sectors: ['Straight', 'Corner', 'Corner', 'Corner', 'Straight', 'Corner', 'Straight', 'Corner'],
  },
  {
    id: 'australia',
    name: '앨버트 파크 서킷',
    country: '호주',
    description: '공원 도로를 활용한 반-시가지 서킷으로 흐름이 중요합니다.',
    characteristics: { downforce: '중간', tireWear: '중간', speed: '높음' },
    baseLapTime: 79.8, 
    idealSetup: { wingAngle: 32, stiffness: 5 },
    sectors: ['Straight', 'Chicane', 'Straight', 'Corner', 'Straight', 'Chicane', 'Straight', 'Corner'],
  },
  {
    id: 'japan',
    name: '스즈카 서킷',
    country: '일본',
    description: '차량의 전체적인 밸런스를 시험하는 테크니컬한 8자 형태의 트랙입니다.',
    characteristics: { downforce: '높음', tireWear: '높음', speed: '중간' },
    baseLapTime: 93.7, 
    idealSetup: { wingAngle: 42, stiffness: 6 },
    sectors: ['Corner', 'Corner', 'Corner', 'Corner', 'Straight', 'Chicane', 'Corner', 'Straight'],
  },
  {
    id: 'china',
    name: '상하이 인터내셔널 서킷',
    country: '중국',
    description: '매우 긴 백스트레이트와 독특한 달팽이형 코너가 특징입니다.',
    characteristics: { downforce: '중간', tireWear: '높음', speed: '높음' },
    baseLapTime: 97.8, 
    idealSetup: { wingAngle: 25, stiffness: 5 },
    sectors: ['Corner', 'Corner', 'Straight', 'Corner', 'Straight', 'Corner', 'Straight', 'Corner'],
  },
  {
    id: 'miami',
    name: '마이애미 인터내셔널 오토드로롬',
    country: '미국',
    description: '경기장 주변을 도는 하이브리드 트랙으로 노면 온도가 높습니다.',
    characteristics: { downforce: '중간', tireWear: '중간', speed: '중간' },
    baseLapTime: 89.4, 
    idealSetup: { wingAngle: 22, stiffness: 4 },
    sectors: ['Straight', 'Corner', 'Straight', 'Corner', 'Chicane', 'Straight', 'Corner', 'Straight'],
  },
  {
    id: 'imola',
    name: '이몰라 (엔초 에 디노 페라리)',
    country: '이탈리아',
    description: '반시계 방향으로 주행하는 클래식 서킷으로 연석 활용이 중요합니다.',
    characteristics: { downforce: '높음', tireWear: '중간', speed: '중간' },
    baseLapTime: 75.9, 
    idealSetup: { wingAngle: 38, stiffness: 4 },
    sectors: ['Straight', 'Chicane', 'Corner', 'Straight', 'Chicane', 'Corner', 'Straight', 'Corner'],
  },
  {
    id: 'monaco',
    name: '모나코 서킷',
    country: '모나코',
    description: '가장 느리고 좁은 시가지 서킷으로 예선 순위가 절대적입니다.',
    characteristics: { downforce: '높음', tireWear: '낮음', speed: '낮음' },
    baseLapTime: 74.5, 
    idealSetup: { wingAngle: 50, stiffness: 2 },
    sectors: ['Corner', 'Corner', 'Corner', 'Straight', 'Corner', 'Corner', 'Chicane', 'Corner', 'Corner'],
  },
  {
    id: 'canada',
    name: '질 빌너브 서킷',
    country: '캐나다',
    description: '가속과 감속이 반복되는 스톱-앤-고 스타일의 서킷입니다.',
    characteristics: { downforce: '낮음', tireWear: '중간', speed: '높음' },
    baseLapTime: 73.8, 
    idealSetup: { wingAngle: 18, stiffness: 3 },
    sectors: ['Straight', 'Chicane', 'Straight', 'Chicane', 'Straight', 'Corner', 'Straight', 'Chicane'],
  },
  {
    id: 'spain',
    name: '바르셀로나-카탈루냐 서킷',
    country: '스페인',
    description: '에어로다이내믹 성능의 기준점이 되는 밸런스 잡힌 트랙입니다.',
    characteristics: { downforce: '높음', tireWear: '높음', speed: '중간' },
    baseLapTime: 76.5, 
    idealSetup: { wingAngle: 45, stiffness: 7 },
    sectors: ['Straight', 'Corner', 'Corner', 'Corner', 'Straight', 'Corner', 'Corner', 'Straight'],
  },
  {
    id: 'austria',
    name: '레드불 링',
    country: '오스트리아',
    description: '짧지만 고저차가 심하며, 3개의 DRS 구간으로 추월이 잦습니다.',
    characteristics: { downforce: '중간', tireWear: '높음', speed: '높음' },
    baseLapTime: 67.8, 
    idealSetup: { wingAngle: 26, stiffness: 6 },
    sectors: ['Straight', 'Corner', 'Straight', 'Corner', 'Corner', 'Straight', 'Corner', 'Straight'],
  },
  {
    id: 'silverstone',
    name: '실버스톤 서킷',
    country: '영국',
    description: '마고트와 베켓 등 초고속 코너가 즐비한 F1의 고향입니다.',
    characteristics: { downforce: '높음', tireWear: '높음', speed: '높음' },
    baseLapTime: 88.5, 
    idealSetup: { wingAngle: 36, stiffness: 7 },
    sectors: ['Corner', 'Straight', 'Corner', 'Corner', 'Straight', 'Corner', 'Straight', 'Corner', 'Corner'],
  },
  {
    id: 'hungary',
    name: '헝가로링',
    country: '헝가리',
    description: '벽 없는 모나코라 불리며, 좁고 구불구불하여 추월이 어렵습니다.',
    characteristics: { downforce: '높음', tireWear: '중간', speed: '낮음' },
    baseLapTime: 78.3, 
    idealSetup: { wingAngle: 48, stiffness: 4 },
    sectors: ['Straight', 'Corner', 'Corner', 'Corner', 'Chicane', 'Corner', 'Corner', 'Straight'],
  },
  {
    id: 'belgium',
    name: '스파-프랑코샹',
    country: '벨기에',
    description: '오루즈 언덕을 포함한 가장 긴 트랙으로 날씨 변수가 큽니다.',
    characteristics: { downforce: '중간', tireWear: '높음', speed: '높음' },
    baseLapTime: 106.2, 
    idealSetup: { wingAngle: 20, stiffness: 6 },
    sectors: ['Straight', 'Corner', 'Straight', 'Corner', 'Corner', 'Straight', 'Corner', 'Chicane'],
  },
  {
    id: 'netherlands',
    name: '잔드보르트 서킷',
    country: '네덜란드',
    description: '뱅킹 코너가 있는 롤러코스터 같은 트랙으로 리듬이 중요합니다.',
    characteristics: { downforce: '높음', tireWear: '높음', speed: '중간' },
    baseLapTime: 72.8, 
    idealSetup: { wingAngle: 44, stiffness: 5 },
    sectors: ['Straight', 'Corner', 'Corner', 'Corner', 'Corner', 'Straight', 'Corner', 'Corner'],
  },
  {
    id: 'monza',
    name: '오토드로모 나치오날레 몬자',
    country: '이탈리아',
    description: '속도의 사원. 극단적으로 낮은 다운포스 세팅이 필요합니다.',
    characteristics: { downforce: '낮음', tireWear: '중간', speed: '높음' },
    baseLapTime: 82.5, 
    idealSetup: { wingAngle: 5, stiffness: 8 },
    sectors: ['Straight', 'Chicane', 'Straight', 'Corner', 'Straight', 'Corner', 'Straight', 'Corner', 'Straight'],
  },
  {
    id: 'baku',
    name: '바쿠 시티 서킷',
    country: '아제르바이잔',
    description: '초장거리 직선과 좁은 성곽 구간이 공존하는 극단적인 서킷입니다.',
    characteristics: { downforce: '낮음', tireWear: '중간', speed: '높음' },
    baseLapTime: 103.5, 
    idealSetup: { wingAngle: 12, stiffness: 3 },
    sectors: ['Corner', 'Corner', 'Corner', 'Straight', 'Chicane', 'Corner', 'Straight', 'Straight'],
  },
  {
    id: 'singapore',
    name: '마리나 베이 스트리트 서킷',
    country: '싱가포르',
    description: '덥고 습한 야간 레이스로 드라이버에게 최고의 체력을 요구합니다.',
    characteristics: { downforce: '높음', tireWear: '높음', speed: '낮음' },
    baseLapTime: 96.5, 
    idealSetup: { wingAngle: 50, stiffness: 3 },
    sectors: ['Straight', 'Corner', 'Corner', 'Straight', 'Corner', 'Corner', 'Straight', 'Corner'],
  },
  {
    id: 'austin',
    name: '서킷 오브 디 아메리카 (COTA)',
    country: '미국',
    description: '오르막 1번 코너와 다양한 고속 코너가 조합된 현대적인 트랙입니다.',
    characteristics: { downforce: '높음', tireWear: '높음', speed: '중간' },
    baseLapTime: 97.2, 
    idealSetup: { wingAngle: 38, stiffness: 6 },
    sectors: ['Straight', 'Corner', 'Corner', 'Straight', 'Corner', 'Corner', 'Corner', 'Straight'],
  },
  {
    id: 'mexico',
    name: '에르마노스 로드리게스',
    country: '멕시코',
    description: '고지대에 위치하여 공기 밀도가 낮아 다운포스 확보가 어렵습니다.',
    characteristics: { downforce: '높음', tireWear: '중간', speed: '높음' },
    baseLapTime: 79.5, 
    idealSetup: { wingAngle: 48, stiffness: 5 },
    sectors: ['Straight', 'Chicane', 'Straight', 'Corner', 'Corner', 'Straight', 'Corner', 'Corner'],
  },
  {
    id: 'brazil',
    name: '인터라고스',
    country: '브라질',
    description: '반시계 방향 주행과 날씨 변화가 심한 클래식 트랙입니다.',
    characteristics: { downforce: '중간', tireWear: '중간', speed: '중간' },
    baseLapTime: 72.1, 
    idealSetup: { wingAngle: 32, stiffness: 5 },
    sectors: ['Straight', 'Chicane', 'Straight', 'Corner', 'Corner', 'Straight', 'Corner', 'Straight'],
  },
  {
    id: 'vegas',
    name: '라스베이거스 스트립 서킷',
    country: '미국',
    description: '라스베이거스 스트립을 관통하는 화려한 초고속 야간 서킷입니다.',
    characteristics: { downforce: '낮음', tireWear: '낮음', speed: '높음' },
    baseLapTime: 94.2, 
    idealSetup: { wingAngle: 10, stiffness: 4 },
    sectors: ['Straight', 'Corner', 'Straight', 'Straight', 'Corner', 'Straight', 'Corner', 'Straight'],
  },
  {
    id: 'qatar',
    name: '루사일 인터내셔널 서킷',
    country: '카타르',
    description: '고속 코너가 끊임없이 이어지며 타이어에 큰 부하를 줍니다.',
    characteristics: { downforce: '높음', tireWear: '높음', speed: '높음' },
    baseLapTime: 84.8, 
    idealSetup: { wingAngle: 35, stiffness: 7 },
    sectors: ['Straight', 'Corner', 'Corner', 'Corner', 'Straight', 'Corner', 'Corner', 'Straight'],
  },
  {
    id: 'abudhabi',
    name: '야스 마리나 서킷',
    country: '아랍에미리트',
    description: '시즌 피날레가 열리는 화려한 서킷으로 섹터별 특성이 다릅니다.',
    characteristics: { downforce: '중간', tireWear: '중간', speed: '중간' },
    baseLapTime: 85.6, 
    idealSetup: { wingAngle: 28, stiffness: 5 },
    sectors: ['Straight', 'Corner', 'Straight', 'Chicane', 'Corner', 'Straight', 'Corner', 'Corner'],
  },
];